name: Jekyll Deploy

on:
  push:
    branches:
      - main  # Deploy from main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.4'

      - name: 📦 Install system dependencies (ImageMagick + Jupyter)
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick libmagickwand-dev python3-pip
          pip3 install notebook jupyter

      - name: Install Ruby dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages  # <-- important!